{% set name = "winkerberos" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/winkerberos-{{ version }}.zip
  sha256: 02ec925c2aa4fe4f7656792a76e346d8fab13e12ced2732354a21958adfe92c6

build:
  skip: true  # [py<36]
  skip: true  # [not win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - sphinx 5.0.2
    - pip 23.0.1
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - winkerberos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mongodb/winkerberos
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: High level interface to SSPI for Kerberos client auth
  description: |
    A native Kerberos client implementation for Python on Windows.
    This module mimics the API of pykerberos to implement Kerberos
    authentication with Microsoft's Security Support Provider Interface (SSPI).
    It supports Python 2.7 and 3.5+.
  doc_url: https://pypi.org/project/winkerberos/
  dev_url: https://github.com/mongodb/winkerberos
extra:
  recipe-maintainers:
    - ocefpaf
