{% set name = "winkerberos" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/winkerberos/winkerberos-0.12.2.tar.gz
  sha256: ff91daed04727a0362892802ee093d8da11f08536393526bdf3bc64e04079faa

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39 or unix]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=61.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - winkerberos
  requires:
    - pip
    - pytest  
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/mongodb/winkerberos
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: High level interface to SSPI for Kerberos client auth
  description: |
    A native Kerberos client implementation for Python on Windows.
    This module mimics the API of pykerberos to implement Kerberos
    authentication with Microsoft's Security Support Provider Interface (SSPI).
    It supports Python 2.7 and 3.5+.
  doc_url: https://pypi.org/project/winkerberos
  dev_url: https://github.com/mongodb/winkerberos

extra:
  recipe-maintainers:
    - ocefpaf
